### ISSUE TITLE
如何安装与使用

### ISSUE THREAD

**Issue by lonelyleaves** [jicg/easypos#1]
请问这个应用是装在什么环境，有没有版本要求，能否提供一份安装文档以供安装测试

**Comment by jicg** [comment]
你好，谢谢您对项目的支持，请[下载我下载安装程序](https://gitee.com/jicg/easypos/attach_files/download?i=68415&u=http%3A%2F%2Ffiles.git.oschina.net%2Fgroup1%2FM00%2F00%2F8C%2FPaAvDFgW1OiADB1YAGcXR5lDvYQ412.zip%3Ftoken%3D92d36b25229039900458efe22692e856%26ts%3D1508724933%26attname%3Deasypos.zip)，安装在wins的环境上。当然，项目也支持其余的系统，您可以了解下golang，需要您自己编译出其他系统的运行程序。
